trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ubuntu/build.ps1
      - ubuntu/iso.pkr.hcl
      - ubuntu/ub2004/*
      - ubuntu/scripts/bootstrap.sh
      - ubuntu/scripts/install-ad.sh

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
  variables:
    - group: packer
  steps:
  - script: pwsh ./build.ps1 -Type iso -Image ub2004
    workingDirectory: $(Build.SourcesDirectory)/ubuntu
    displayName: 'Build Ubuntu 20.04 packer image'
    env:
      VSPHERE_USER: $(vsphere.username)
      VSPHERE_PASS: $(vsphere.password)
      ADMIN_PASS: $(admin.password)