trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ubuntu/build.ps1
      - ubuntu/iso.pkr.hcl
      - ubuntu/ub2004/*
      - ubuntu/scripts/bootstrap.sh
      - ubuntu/scripts/install-ad.sh

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
  steps:
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'GLabConfig'
      KeyFilter: '*'
      Label: 'vcenter'
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'GLabConfig'
      KeyFilter: '*'
      Label: 'packer'
  - script: pwsh ./build.ps1 -Type iso -Image ub2004
    workingDirectory: $(Build.SourcesDirectory)/ubuntu
    displayName: 'Build Ubuntu 20.04 packer image'
    env:
      VCENTER_USER: $(vcenter.username)
      VCENTER_PASS: $(vcenter.password)
      ADMIN_PASS: $(packer.admin.password)