trigger:
  branches:
    include:
      - master
  paths:
    include:
      - windows/build.ps1
      - windows/iso.pkr.hcl
      - windows/ws2016gui/*
      - windows/scripts/change-pass.ps1
      - windows/scripts/enable-rdp.ps1
      - windows/scripts/enable-winrm.ps1
      - windows/scripts/install-vm-tools.ps1
      - windows/scripts/undo-winrmconfig.ps1

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
  variables:
    - group: packer
  steps:
  - script: pwsh ./build.ps1 -Type iso -Image ws2016gui
    workingDirectory: $(Build.SourcesDirectory)/windows
    displayName: 'Build Windows Server 2016 GUI packer image'
    env:
      VSPHERE_USER: $(vsphere.username)
      VSPHERE_PASS: $(vsphere.password)
      ADMIN_PASS: $(admin.password)