trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ubuntu/build.ps1
      - ubuntu/clone.pkr.hcl
      - ubuntu/ubagent/*

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
    demands:
      - agent.os -equals Linux
  steps:
  - script: pwsh ./build.ps1 -Type clone -Username administrator@vsphere.local -VspherePassword $(vsphere.password) -AdminPassword $(admin.password) -Image ubagent
    workingDirectory: $(Build.SourcesDirectory)/ubuntu
    displayName: 'Build Azure DevOps Ubuntu agent packer image'