trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ubuntu/build.ps1
      - ubuntu/clone.pkr.hcl
      - ubuntu/ubagent/*

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
    demands:
      - agent.os -equals Linux
  steps:
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'LabConfig'
      KeyFilter: '*'
      Label: 'vcenter'
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'LabConfig'
      KeyFilter: '*'
      Label: 'packer'
  - script: pwsh ./build.ps1 -Type clone -Image ubagent
    workingDirectory: $(Build.SourcesDirectory)/ubuntu
    displayName: 'Build Azure DevOps Ubuntu agent packer image'
    env:
      VCENTER_USER: $(vcenter.username)
      VCENTER_PASS: $(vcenter.password)
      ADMIN_PASS: $(packer.admin.password)