trigger:
  branches:
    include:
      - master
  paths:
    include:
      - ubuntu/build.ps1
      - ubuntu/clone.pkr.hcl
      - ubuntu/ubagent/*

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
    demands:
      - agent.os -equals Linux
  variables:
    - group: packer
    - group: vcenter
  steps:
  - script: pwsh ./build.ps1 -Type clone -Image ubagent
    workingDirectory: $(Build.SourcesDirectory)/ubuntu
    displayName: 'Build Azure DevOps Ubuntu agent packer image'
    env:
      VSPHERE_USER: $(vcenter.username)
      VSPHERE_PASS: $(vcenter.password)
      ADMIN_PASS: $(packer.admin.password)