trigger:
  branches:
    include:
      - master
  paths:
    include:
      - windows/build.ps1
      - windows/clone.pkr.hcl
      - windows/wsagent/*
      - windows/scripts/change-pass.ps1
      - windows/scripts/enable-winrm.ps1
      - windows/scripts/undo-winrmconfig.ps1

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
    demands:
      - agent.os -equals Linux
  variables:
    - group: packer
    - group: vcenter
  steps:
  - script: pwsh ./build.ps1 -Type clone -Image wsagent
    workingDirectory: $(Build.SourcesDirectory)/windows
    displayName: 'Build Azure DevOps Windows agent'
    env:
      VSPHERE_USER: $(vcenter.username)
      VSPHERE_PASS: $(vcenter.password)
      ADMIN_PASS: $(packer.admin.password)