trigger:
  branches:
    include:
      - master
  paths:
    include:
      - windows/build.ps1
      - windows/clone.pkr.hcl
      - windows/wsagent/*
      - windows/scripts/change-pass.ps1
      - windows/scripts/enable-winrm.ps1
      - windows/scripts/undo-winrmconfig.ps1

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
    demands:
      - agent.os -equals Linux
  steps:
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'LabConfig'
      KeyFilter: '*'
      Label: 'vcenter'
  - task: AzureAppConfiguration@3
    inputs:
      azureSubscription: 'Lab Resource Group'
      ConfigstoreName: 'LabConfig'
      KeyFilter: '*'
      Label: 'packer'
  - script: pwsh ./build.ps1 -Type clone -Image wsagent
    workingDirectory: $(Build.SourcesDirectory)/windows
    displayName: 'Build Azure DevOps Windows agent'
    env:
      VCENTER_USER: $(vcenter.username)
      VCENTER_PASS: $(vcenter.password)
      ADMIN_PASS: $(packer.admin.password)