trigger:
  branches:
    include:
      - master
  paths:
    include:
      - windows/*
    exclude:
      - windows/ws2016gui/*

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: Lab
  steps:
  - script: powershell ./build.ps1 -Type iso -Username administrator@vsphere.local -Password $(vsphere.password) -Image ws2016core
    workingDirectory: $(Build.SourcesDirectory)/windows
    displayName: 'Build Windows Server 2016 Core packer image'