trigger:
  branches:
    include:
      - master
  paths:
    include:
      - packer/windows/*
    exclude:
      - packer/windows/ws2016gui/*

jobs:
- job: Default
  timeoutInMinutes: 120
  pool:
    name: default
  steps:
  - script: powershell ./build.ps1 -Username administrator@vsphere.local -Password $(vsphere.password) -Image ws2016core
    workingDirectory: $(Build.SourcesDirectory)/packer/windows
    displayName: 'Build Windows Server 2016 Core packer image'